### ISSUE TITLE
How to use this mod 22w15a

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [quiqueck/wunderreich#1]
Minecraft: fabric-loader-0.13.3-22w15a

Please provide a guide, how to get started.
There are no recipes in 22w15a

mfg
daniel

**Comment by quiqueck** [comment]
Hi. and thanks for contacting me. 

Could you maybe provide the fabric log file. I just checked, and the recipes do show up in 22w15a. So there may be a configuration issue.

**Comment by MUHAKLorTheDorfTrottel4Github** [comment]
[latest.log](https://github.com/quiqueck/wunderreich/files/8508216/latest.log)

Mir ist unklar, wie ich ueberhaupt anfangen soll.
Ich spiel 98% single survival, cheats nur wegen locate 
mfg

**Comment by quiqueck** [comment]
Das Log sieht soweit in Ordnung aus. Der Mod ist geladen und sollte ohne weitere config funktionieren. Die Rezepte werden aber normalerweise erst angezeigt wenn Schlüsselrohstoffe gefunden werden. Das Rezept für die Spachtel sollte z.B. Im Rezeptbuch verfügbar sein sobald ein Eisenbarren im Spielerinventar war.

**Comment by MUHAKLorTheDorfTrottel4Github** [comment]
danke fuer Feedback
In anderen Mods sind die Rezepte als .json definiert
Da kann man nachkucken (>data>recipes)
Sie machen das mit JAVA class 
Solange in snapshot 22wxx kein JEI/REI verfuegbar ist, die einzige gangbare Loesung

Als Anhang noch ein Raetsel fuer mich

Was mache ich mit dem "imprinted whisperer"

mfg 
daniel aus München

![Plug_and_Pray_1](https://user-images.githubusercontent.com/18631808/163898993-a0f9b402-16aa-4b37-82b6-a4dc9fff972a.jpg)

**Comment by MUHAKLorTheDorfTrottel4Github** [comment]
nocheiner

![Plug_and_Pray_2](https://user-images.githubusercontent.com/18631808/163901177-cf86b28d-7249-4c67-bcb3-ac746fc30bfe.jpg)

Ich will nicht kritisieren, nur helfen
==========================================================

PS: es gibt bisjetz KEINEN mod, der INFO ueber ein DORF ausspuckt,
e.g size, anzahl villager, anzahl nitwit, unimploid etc.

Koennte ein Villager sein, der Concierge oder Dorfbulle heisst, bein anklicken
popup info GUI
 
mfg

**Comment by quiqueck** [comment]
Alles gut 👍, nehm ich nicht als Kritik, sondern Anregungen wahr. Und manches ist ja immer nur dem Entwickler und sonst niemanden auf der Welt klar :D

Beim Prägen muss ich wohl nochmal sehen, dass das am besten passende Rezept ausgesucht wird oder das alle Rezepte eindeutig sind (was mit Mods die neue Verzauberungen einfügen vermutlich schwierig werden könnte...). Bis dahin sollte es aber Funktionieren, wenn ein Eintrag aus der Liste links angeklickt wird, dann müsste rechts der korrekt geprägte Flüstere erscheinen. Falls der leere Flüstere schon gebraucht wurde, dann muss er von Hand eingelegt werden.

Beim 2. Bild hat der Dörfler schon Erfahrung. Deswegen kann der Handel nicht mehr getauscht werden.

**Comment by MUHAKLorTheDorfTrottel4Github** [comment]
![Plug_and_Pray_43](https://user-images.githubusercontent.com/18631808/163956997-6922714f-bc5e-4a32-ad96-cd0a725d6eed.jpg)

Vorgehen:
dorfbewohner gefangen > in "zelle" plaziert  ( mit gobber Staff ensnarement)
rechtsklick > dorfbewohner schüttelt kopf = dumm , arbeitslos
Lectern plaziert > dorfbewohner hat verz. Buch im Angebot

 
![Plug_and_Pray_3](https://user-images.githubusercontent.com/18631808/163957933-f1f07094-e207-4343-b2da-6fb3938395e7.jpg)

Ich aendere die verzauberung bisjetzt, indem ich den lechtern wegnehme und wieder
plaziere. Geht nicht mehr wenn bereits gehandelt. 
Wenn nicht das erste Angebot gehandelt wird, geht Sie verloren ( wahrsch. Uebernacht)

Ich seh nach wie vor KEIN Symbol zum aendern.
? muss ich einen Imprinted Whisperer anbieten?

Frage : Haelt die WUNDERKISTE den jew. Chunk AKTIV, wenn der Spieler
                NICHT da ist ( quasi chunkloader, hintergrund ofen, mobfarm output)

mfg
daniel

**Comment by quiqueck** [comment]
Ein Spieler muss den gewünschten Flüsterer in der Hand haben wenn man mit den Dörflern handelt.


Die Wunderkiste ist im Moment kein chunkloader. Derzeit "kommunizieren" die Kisten über einen anderen Kanal. Aber das chunk-loading steht mit auf meiner Liste von Dingen die ich mir dafür ansehen will...
