### ISSUE TITLE
22w15a WUNDERKISTE

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [quiqueck/wunderreich#2]
fabric-loader-0.13.3-22w15a
fabric-api-0.51.0+1.19.jar
wunderreich-1.0.0-15a.jar

WUNDERKISTE:
-does not update, if player is not near ( not even in Spawn chunk )
  place a vanilla furnace in spawn chunk, burn something, result with hopper to wunderkiste
  teleport away, place second wunderkiste ,open 
-have 1 sec delay to open
  place wunderkiste and enderchest, open both
- don't update GUI when open 
   content updated, just visual no update, update, seems to update gui  only on open.event

I would like the WUNDERKISTE, like an enhanced enderchest ( which ignores hoppers etc.) 
 
regards
daniel

**Comment by quiqueck** [comment]
Sorry for taking so long. But (if I understand correctly) I think this may be related to vanilla behaviour.

- Furnaces do not work when no player is near - even in a spawn chunk. 
- When the Wunderkiste is opened, all Wunderkisten in the world will emit redstone power, which will lock connected hoppers

But please correct me if I am wrong or if i missunderstood the report :)

**Comment by MUHAKLorTheDorfTrottel4Github** [comment]
you wrote:
When the Wunderkiste is opened, all Wunderkisten in the world will emit redstone power, which will lock connected hoppers

? (1) Do they emit redstone in NOT ACTIVE CHUNKS (to use as chunkloader)
? (2) do they emit on all 6 sides ( to use as "wireless redstone")

regard

**Comment by quiqueck** [comment]
**(1)** Version 1.0.7 makes the Wunderkiste a proper cross-dimensional chunk loader. The loaded chunks will tick blocks but do not spawn entities (or keep the alive). By default the chunk where the Wunderkiste was placed is loaded. 

You can use the gamerule `\wunderkisteChunkLoaderRadius <radius>` to define chunk radius (0=disabled, 1=default)

**(2)** Yes, they emit on all 6 sides
