### ISSUE TITLE
[Crash]: when disabling glass_slab + recipes

### ISSUE THREAD

**Issue by xR4YM0ND** [quiqueck/wunderreich#3]
i disabled glass_slab in block.json and all of the recipes in recipe.json

the game crashes cause of block air something 

[latest.log](https://gist.github.com/SpigotDE/086b693eb58a8560e9792d738c923675)

**Comment by quiqueck** [comment]
Hi and thanks for reporting. I'll look into it.

**Comment by quiqueck** [comment]
Thanks again for taking the time to report this. Itshould be fixed with the just released 1.0.4 update.

**Comment by xR4YM0ND** [comment]
Thank you for making the mod and replying and fixing <3
