### ISSUE TITLE
Imprinted whisperer not working (1.19)

### ISSUE THREAD

**Issue by clmc99** [quiqueck/wunderreich#4]
Tried to use a Wunderreich imprinted whisper on a villager and the trades just kept rerolling randomly.  The wunderreichAllowLibrarianSelection gamerule is true, config has not been altered, and the only mods present are Architectury, Cloth Config, Fabric API, Mod Menu, REI, and Wunderreich.

**Comment by quiqueck** [comment]
Thank you for reporting. This is fixed in 1.0.8.

**Comment by clmc99** [comment]
Thanks!
