### ISSUE TITLE
Wunderreich Crashing my Game when additional slabs is set to off.

### ISSUE THREAD

**Issue by dalekfan** [quiqueck/wunderreich#5]
Seems I can't load my game anymore with the mod installed since it keeps giving this error as soon as MC loads.
_**"The game crashed whilst initializing game Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1935.method_8389()" because "$$2" is null Exit Code: -1"**_

Crashlog here
[crash-2022-06-18_17.41.39-client.txt](https://github.com/quiqueck/wunderreich/files/8934397/crash-2022-06-18_17.41.39-client.txt)
.

It's most likely a mod compat issue.

**Comment by quiqueck** [comment]
Thanks for reporting. You can manually edit the config-file located in `.minecraft/config/wunderreich/main.json`. Open it with a text editor (like Notepad) and change the line `"addSlabs": false,` setting to  `"addSlabs": true,`.

**Comment by quiqueck** [comment]
Fixed in release 3.0.8
