### ISSUE TITLE
[Fabric 1.18.2] Full block slabs only drop 1 slab.

### ISSUE THREAD

**Issue by kingkuys2123** [quiqueck/wunderreich#6]
Minecraft 1.18.2
Fabric Loader 0.14.9
Fabric Api 0.59.0

Wunderreich v2.0.13

>> When placing slabs of this mod and making them full blocks (2 slabs), they only drop 1 slab when mined. 

>> other issue is, (I don't know if this is intentional for this mod) the glass slabs should be obtainable with tool that has Silk Touch enchantment

![2022-10-06_16 23 53](https://user-images.githubusercontent.com/114457180/194261240-b3b054c1-a2d0-4f2f-a561-db15ceb26ed2.png)
![2022-10-06_16 24 30](https://user-images.githubusercontent.com/114457180/194261249-52df1808-2552-4d30-ac31-3357e3e64768.png)

**Comment by quiqueck** [comment]
Thanks for reporting. I will look into that.

**Comment by quiqueck** [comment]
Fix is released as 3.0.16
